### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by DavidMChan** [DavidMChan/DUDL#4]
Traceback (most recent call last):
  File "test_pca_cross_entropy_loss_based_cnn.py", line 107, in <module>
    pred=lambda f: mpx in f)
  File "/home/david/Research/ML/LabelSmoothing/DUDL/utils/filesystem_util.py", line 34, in find_best_model
    str.isdigit, f)))) [-1]
IndexError: list index out of range

(dudl/examples/test_pca)

**Comment by psnegi** [comment]
we need to fix the scenario when no best model was saved due to higher threshold setting for  best_val_accuracy. 
For time being lower the value of  best_val_accuracy = .8 in DNN

**Comment by psnegi** [comment]
fixed . commit [cebc300](https://github.com/DavidMChan/DUDL/commit/cebc3001ab320db98c26aadd9157678b75585e38)

Also. json file format have more parameters now.
